# Generated by Django 4.2 on 2024-03-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_credits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
