# Generated by Django 4.2 on 2024-03-20 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpayment',
            old_name='date_added',
            new_name='date',
        ),
    ]
