# Generated by Django 4.2 on 2024-03-21 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_date_added_customerpayment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerpayment',
            old_name='credit',
            new_name='payment_credit',
        ),
    ]
