# Generated by Django 4.2 on 2024-03-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_credit_customerpayment_payment_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_credit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
