# Generated by Django 4.2 on 2024-03-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_covergenerator'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='home')),
                ('prompt', models.TextField()),
                ('cover_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='covergenerator',
            name='cover',
            field=models.ImageField(upload_to='users'),
        ),
    ]
