# Generated by Django 4.2 on 2024-03-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_covergenerator_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covergenerator',
            name='cover',
            field=models.ImageField(blank=True, upload_to='users'),
        ),
        migrations.AlterField(
            model_name='covergenerator',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
