# Generated by Django 4.2 on 2024-04-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_covergenerator_cover_alter_covergenerator_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='covergenerator',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='payment_credit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
