# Generated by Django 4.2 on 2024-04-10 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEditing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.ImageField(upload_to='images-edit/')),
                ('blank', models.ImageField(upload_to='images-edits/blanks/')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('font', models.CharField(choices=[('Roboto', 'Roboto'), ('ZCOOL', 'ZCOOL')], default='Roboto', max_length=100)),
                ('size', models.IntegerField(default=10)),
                ('color', models.CharField(max_length=100)),
                ('alt_text', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='app.covergenerator')),
            ],
        ),
    ]
