# Generated by Django 4.2 on 2024-05-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentfeature',
            name='payment',
        ),
        migrations.AddField(
            model_name='paymentfeature',
            name='payment',
            field=models.ManyToManyField(blank=True, default=None, related_name='payment_plan', to='app.payment'),
        ),
    ]
